site_name: Imaging w/ data-driven models
pages:
    - Topics: outline.md
    - Assigments: homework.md
    - Projects: project.md

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

